 export const tasks = [
  {
    id: 1,
    title: "Complete React Project",
    description: "Finish the user interface and backend integration for the React application.",
    date: "2025-01-27",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 2,
    title: "Prepare Presentation",
    description: "Prepare slides and practice for the upcoming client presentation.",
    date: "2025-01-28",
    priority: "Medium",
    status: "Not Started",
  },
  {
    id: 3,
    title: "Team Meeting",
    description: "Discuss project milestones and upcoming tasks with the team.",
    date: "2025-01-29",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 4,
    title: "Fix UI Bugs",
    description: "Resolve CSS layout and responsiveness issues on the dashboard.",
    date: "2025-01-30",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 5,
    title: "Database Backup",
    description: "Schedule and take a backup of the database to avoid data loss.",
    date: "2025-01-31",
    priority: "Low",
    status: "Not Started",
  },
  {
    id: 6,
    title: "Code Review",
    description: "Review code submitted by the team and provide feedback.",
    date: "2025-02-01",
    priority: "Medium",
    status: "In Progress",
  },
  {
    id: 7,
    title: "Update Documentation",
    description: "Update the project documentation to reflect recent changes.",
    date: "2025-02-02",
    priority: "Low",
    status: "Not Started",
  },
  {
    id: 8,
    title: "Release New Feature",
    description: "Deploy the new feature to production and monitor for any issues.",
    date: "2025-02-03",
    priority: "High",
    status: "Pending Approval",
  },
  {
    id: 9,
    title: "Test API Endpoints",
    description: "Perform unit and integration testing on all API endpoints.",
    date: "2025-02-04",
    priority: "High",
    status: "In Progress",
  },
  {
    id: 10,
    title: "Client Feedback",
    description: "Gather and analyze feedback from the client for improvements.",
    date: "2025-02-05",
    priority: "Medium",
    status: "Not Started",
  },
];


